#!/usr/bin/env bash
# my duty is to print subdomains info

infor_her () {
	args=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $args" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" -eq 2 ]; then
	infor_her "$1" "$2"
else
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdom in "${subdomains[@]}"; do
		infor_her "$1" "$subdom"
	done
fi
