#!/usr/bin/env bash
# setting up nginx for redirect to different web page


sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World" > /var/www/html/index.html
sudo sed -i "/^\sserver_name.*/a \    rewrite ^/redirect_me(/*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "/^\slocation.*/i \        error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
sudo service nginx restart
