#!/usr/bin/env bash
# this script installs and conf Haproxy

sudo service haproxy stop
sudo apt-get purge -y haproxy

sudo apt update
sudo apt install -y haproxy

sudo sed -i '$aENABLED=1' /etc/default/haproxy

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
	log /dev/log local0
	log /dev/log local1 notice
	user haproxy
	group haproxy
	maxconn 2000
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	retries 3
	timeout http-request 10s
	timeout queue 1m
	timeout connect 10s
	timeout client 1m
	timeout server 1m
	timeout check 10s

frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server 259414-web-01 54.173.2.214:80 check
	server 259414-web-02 100.24.242.66:80 check
EOL

sudo service haproxy restart
sudo service haproxy enable
