#!/usr/bin/env bash
# This script contrals all

process_name="manage_my_process"
pid_file="/var/run/my_process.pid"

start()
{
	if [ -f "$pid_file" ]; then
		echo "$process_name is already running with PID $(cat "$pid_file")"
	else
		./"$process_name" >/dev/null 2>&1 &
		echo $! > "$pid_file"
		echo "$process_name started"
	fi
}

stop()
{
	if [ -f "$pid_file" ]; then
		pid=$(cat "$pid_file")
		rm "$pid_file"
		kill "$pid"
		echo "$process_name stopped"
	else
		echo "$process_name is not running"
	fi
}

restart()
{
	stop
	start
	echo "$process_name restarted"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
